  
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run Maven Test

on:
  push:
    branches: [pliem1991-patch-1, master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install with Maven
      run: |
        mvn install -DskipTests
    - name: Test with Maven  # Cháº¡y test 
      run: mvn test -DargLine=-javaagent:${HOME}/.m2/repository/org/jmockit/jmockit/${JMOCKIT_VERSION}/jmockit-${JMOCKIT_VERSION}.jar
      env:
        JMOCKIT_VERSION: 1.44
